export const testTribeData = {
  image: 'https://www.coralia-liveaboard.com/wp-content/uploads/2020/05/Abui-tribe-dance-in-Alor-with-Coralia-Liveaboard-in-Indonesia.jpg',
  title: 'Tribe Name',
  description: 'Located At: Location',
  researcher: 'Thomas P. Patterson',
  action: {
    type: "internal",
    route: 'tribe/more',
    color: "info",
    label: "know more"
  },
  etymology: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas cursus mattis est sed fermentum. Nullam bibendum ante risus, in condimentum lorem aliquam nec. Proin non convallis nunc, eget tincidunt arcu. Donec porta iaculis nisl, sit amet tincidunt turpis lobortis sed. Nullam suscipit lacus quis ipsum vehicula dictum. Vivamus rutrum dolor non dictum mollis. Ut sit amet sem orci. Donec ac orci scelerisque, gravida mauris non, commodo massa. Nullam nec dolor urna. Donec orci sapien, finibus nec massa quis, aliquam malesuada elit. Phasellus pellentesque erat suscipit, scelerisque ante nec, aliquam ligula. Etiam libero arcu, venenatis at consequat non, tincidunt a purus. Suspendisse in orci viverra, finibus elit non, viverra massa.',
  history: 'Proin in enim vel ipsum porttitor venenatis ac ut lacus. Cras faucibus ipsum quam, quis facilisis dolor efficitur eget. Nam sit amet vulputate mauris, vitae imperdiet tellus. Suspendisse potenti. Vivamus libero purus, vestibulum ut odio a, ullamcorper rutrum turpis. Nullam id ante ullamcorper, tempor justo vel, molestie dolor. Maecenas imperdiet neque eget mi convallis, quis ultricies est venenatis. Maecenas dictum consequat justo eu sodales. Nulla varius blandit fermentum. Integer vitae nisl tincidunt, gravida purus a, tempus leo. Aliquam erat volutpat. Sed convallis massa justo, vel rutrum dolor dapibus a.',
  culture: 'Aenean mollis malesuada mauris, non hendrerit odio lacinia sed. Suspendisse tristique imperdiet iaculis. Cras feugiat dui orci, ac sodales massa vulputate at. Nunc mattis massa urna, in vulputate mauris ullamcorper ac. Fusce mollis auctor ipsum, fermentum ultrices augue pharetra ut. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed quam dui, mollis vitae aliquam malesuada, mollis sit amet augue. Etiam non ullamcorper felis, ut porttitor massa. Duis ut vulputate nulla, et viverra nunc. In consectetur nisl molestie diam maximus, nec ullamcorper turpis consequat.',
  education: 'Praesent maximus dapibus convallis. Suspendisse lacinia fringilla sapien, vitae euismod nulla finibus in. Donec blandit ligula at felis gravida, a porttitor purus placerat. Suspendisse potenti. Mauris purus mauris, lobortis vitae nunc vel, ultrices ullamcorper eros. Proin tincidunt, arcu at egestas bibendum, nisl erat consequat dolor, nec scelerisque dui dolor non lorem. Donec efficitur velit lacinia justo convallis laoreet. Nunc mollis eu ligula tristique tempus.',
  economy: 'Donec rutrum hendrerit diam sagittis accumsan. Sed erat justo, ultrices a tempus a, volutpat nec massa. Curabitur cursus nisi a tellus tempus, et porta purus ultrices. Fusce vitae nibh mauris. Nam arcu risus, eleifend vel blandit ac, tristique ut mauris. Fusce rhoncus erat nec purus tristique, a varius tortor tincidunt. Sed quis ex mi. Aliquam placerat ex eu nibh sodales placerat. Nunc maximus tempus iaculis. Sed laoreet bibendum pharetra. Suspendisse turpis nunc, consectetur ut justo eget, ultricies eleifend tortor. Phasellus dignissim, mi ut sollicitudin vestibulum, dolor neque accumsan purus, vitae vulputate sem ex a odio. Nulla facilisi.'
}
